services:
  go-app:
    container_name: my-app
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@go_db:5432/postgres?sslmode=disable"
      SQL_FILE_PATH: "/internal/storage/migrations/001_create_users_table.sql"
      JWT_SECRET: "intel"
      APP_PASSWORD: "owpkzmwnoxmhhikg"
      TIMEOUT: 4s
      IdleTimeout: 60s
      ENV: "prod"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
networks:
  default:
    driver: bridge
